name: Build iOS and Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: cd ios && pod install

      - name: Install Apple Certificate and Provisioning Profile
        run: |
          echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "" build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS
        run: |
          cd ios
          xcodebuild -workspace AppIngenia.xcworkspace -scheme AppIngenia -configuration Release -archivePath AppIngenia.xcarchive archive -allowProvisioningUpdates

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive -archivePath AppIngenia.xcarchive -exportOptionsPlist exportOptions.plist -exportPath .

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AppIngenia-iOS
          path: ios/AppIngenia.ipa

  build-android:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.java.home=$JAVA_HOME
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AppIngenia-Android
          path: android/app/build/outputs/apk/release/app-release.apk
