name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: cd ios && pod install

      - name: Build iOS
        run: |
          cd ios
          export CODE_SIGN_IDENTITY=""
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGNING_ALLOWED=NO
          xcodebuild -workspace AppIngenia.xcworkspace -scheme AppIngenia -configuration Release -archivePath AppIngenia.xcarchive archive

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive -archivePath AppIngenia.xcarchive -exportOptionsPlist exportOptions.plist -exportPath .

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AppIngenia-iOS
          path: ios/AppIngenia.ipa
